### ISSUE TITLE
Creating private project repositories

### ISSUE THREAD

**Issue by rwest** [CHME5137/github-assignment#3]
@sambamurthyr @KareemAbdelshafy @CFulco:
You are not yet on a "team" associated with a project repository. (we set these up in class yesterday)
Please reply below with your project summary, and I'll set it up.

**Comment by CFulco** [comment]
Hello professor West,


The project I am working on is examining pH levels in small-scale
bioreactors. My goal is to have a somewhat "interactive" model where the
user would either input an acceptable range of pH values and receive the
optimal times to adjust with a specific amount of base, or input a list of
times that an adjustment will take place and have the model return the
calculated base additions at those specific times based on what the pH
would be.


- Cameron

**Comment by KareemAbdelshafy** [comment]
Sorry for the late reply.
I am trying to study the nonlinear dynamics of a system of coupled nonlinear oscillators. For this purpose, I am using python package [PyDSTool](http://www.ni.gsu.edu/~rclewley/PyDSTool/FrontPage.html) to do the continuation and bifurcation analysis.

**Comment by sambamurthyr** [comment]
Sorry about the late reply.
My project will be a monitoring study of the Biogas production from semi-continuous Anaerobic digestion. The levels of gas produced depends on the  levels of ammonium ion concentration in the reactor. The project will help in modelling this relationship. wherein a user could predict the potential gas production rates depending upon the ion concentration or vice versa.
